"""Data models for the llm-vs-rag-bench benchmark system."""

from dataclasses import dataclass, field
from typing import List, Optional
from enum import Enum


class QuestionType(str, Enum):
    """Categories of questions in UniDoc-Bench dataset."""
    FACTUAL_RETRIEVAL = "factual_retrieval"
    SUMMARIZATION = "summarization"
    CAUSAL_REASONING = "causal_reasoning"
    COMPARISON = "comparison"
    TEMPORAL_COMPARISON = "temporal_comparison"


class AnswerType(str, Enum):
    """Required answer formats in UniDoc-Bench dataset."""
    IMAGE_ONLY = "image_only"
    TEXT_ONLY = "text_only"
    TABLE_REQUIRED = "table_required"
    IMAGE_PLUS_TEXT_AS_ANSWER = "image_plus_text_as_answer"


@dataclass
class DocumentPage:
    """Represents a single page of a document.
    
    Attributes:
        image_path: Path to the PNG image file (e.g., 'images/healthcare/1851094/1851094_page_0001.png')
        page_number: Page number within the document (1-indexed)
    """
    image_path: str
    page_number: int


@dataclass
class Document:
    """Represents a full document from UniDoc-Bench.
    
    Attributes:
        doc_id: Unique identifier for the document (extracted from image paths)
        domain: Domain category (e.g., 'healthcare', 'finance', 'legal')
        pages: List of document pages in order
        domain: Domain category this document belongs to
    """
    doc_id: str
    domain: str
    pages: List[DocumentPage] = field(default_factory=list)
    
    @property
    def page_count(self) -> int:
        """Return the total number of pages in this document."""
        return len(self.pages)
    
    @property
    def image_paths(self) -> List[str]:
        """Return list of all image paths in page order."""
        return [page.image_path for page in self.pages]


@dataclass
class Question:
    """Represents a question from UniDoc-Bench dataset.
    
    Attributes:
        question_id: Unique identifier for the question
        text: The actual question text
        question_type: Category of reasoning required
        answer_type: Required format for the answer
        ground_truth_answer: The ground truth answer text
        gt_image_paths: Paths to specific page(s) containing the answer
        domain: Domain category this question belongs to
        document: The source document this question refers to
    """
    question_id: str
    text: str
    question_type: QuestionType
    answer_type: AnswerType
    ground_truth_answer: str
    gt_image_paths: List[str]
    domain: str
    document: Document
    
    @property
    def answer_page_paths(self) -> List[str]:
        """Return paths to pages that contain the answer."""
        return self.gt_image_paths


@dataclass
class BenchmarkResult:
    """Placeholder for benchmark results (to be filled in later phases).
    
    Attributes:
        pipeline_name: Name of the pipeline (e.g., 'llm-wiki-agent', 'rag')
        question_id: ID of the question being evaluated
        predicted_answer: The answer generated by the pipeline
        latency_seconds: Time taken to generate the answer
        token_usage: Number of tokens used (input + output)
        retrieval_count: Number of documents/pages retrieved
        score: LLM-as-Judge score (1-5)
        trajectory: Raw trajectory/thought process from the pipeline
    """
    pipeline_name: str
    question_id: str
    predicted_answer: str
    latency_seconds: float
    token_usage: int
    retrieval_count: int
    score: Optional[float] = None
    trajectory: Optional[dict] = None


@dataclass
class Trajectory:
    """Placeholder for agent trajectory data (for SFT export).
    
    Attributes:
        question_id: ID of the question
        messages: List of conversation messages in OpenAI format
        metadata: Additional metadata about the trajectory
    """
    question_id: str
    messages: List[dict] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
